version: '3.4'

services:

  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=eshop
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=mrahmat_public@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  postgres:
  pgadmin: